const GITHUB_TOKEN = process.env.GITHUB_TOKEN!;
const GITHUB_ORG = process.env.GITHUB_ORG || "vexcraft-io";
const TEMPLATE_REPO = "vexcraft-landing-page-template";

export interface GitCommit {
  sha: string;
  message: string;
  author: string;
  timestamp: string;
  filesChanged: string[];
}

async function githubFetch(path: string, options: RequestInit = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...(options.headers ?? {}),
    },
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`GitHub API error ${res.status} on ${path}: ${err}`);
  }

  if (res.status === 204) return null;
  return res.json();
}

export async function createLandingPageRepo(
  orderId: string,
  customerName: string
): Promise<{ repoUrl: string; cloneUrl: string; repoName: string }> {
  const repoName = `landing-page-${orderId}`;

  // Create blank private repo (agent will scaffold Next.js from scratch)
  await githubFetch(`/orgs/${GITHUB_ORG}/repos`, {
    method: "POST",
    body: JSON.stringify({
      name: repoName,
      description: `Landing page for ${orderId} — ${customerName}`,
      private: true,
      auto_init: true, // Creates initial commit so repo is cloneable
    }),
  });

  // Wait for repo to be ready
  await new Promise((r) => setTimeout(r, 2000));

  // Set topics
  await githubFetch(`/repos/${GITHUB_ORG}/${repoName}/topics`, {
    method: "PUT",
    body: JSON.stringify({ names: ["vexcraft", "landing-page", "generated"] }),
  }).catch(() => {});

  return {
    repoName,
    repoUrl: `https://github.com/${GITHUB_ORG}/${repoName}`,
    cloneUrl: `https://github.com/${GITHUB_ORG}/${repoName}.git`,
  };
}

export async function pushBriefFile(
  repoName: string,
  orderId: string,
  customerName: string,
  brief: string,
  techStack: Record<string, string> | null
): Promise<void> {
  const techSection = techStack
    ? `
## Tech Stack

| Layer | Choice |
|-------|--------|
| Frontend | ${techStack.frontend || "—"} |
| Backend | ${techStack.backend || "—"} |
| Database | ${techStack.database || "—"} |
| Hosting | ${techStack.hosting || "—"} |
`
    : "";

  const content = `# Vexcraft Order Brief

**Order ID:** ${orderId}
**Customer:** ${customerName}
${techSection}
## Customer Brief

${brief || "No brief provided."}

---

> This file is auto-generated by Vexcraft. Use it as the source of truth when building this landing page.
> Match the customer's described style, colors, and goals exactly.
`;

  const briefEncoded = Buffer.from(content).toString("base64");

  const agentsMd = `# Agent Instructions

This repository is a Vexcraft customer landing page project.

## Build & Run
\`\`\`bash
npm install
npm run dev      # dev server on port 3000
npm run build    # production build — must pass before pushing
\`\`\`

## Rules
- Read VEXCRAFT_BRIEF.md before writing any code — it is the source of truth
- Run \`npm run build\` and verify it passes before every \`git push\`
- After every push, wait for Vercel to deploy and verify the result
- Make small, focused commits — one feature at a time
- Never skip the push step — customers only see deployed code
`;

  const claudeMd = `# CLAUDE.md

## Project
Vexcraft customer landing page. Requirements are in VEXCRAFT_BRIEF.md.

## Stack
- Next.js (App Router) + TypeScript
- Tailwind CSS
- Deployed on Vercel — every push to main triggers a deployment

## Commands
\`\`\`bash
npm run dev      # local dev
npm run build    # verify before pushing — must pass with zero errors
npm run lint     # lint check
\`\`\`

## Critical Rules
- Always \`npm run build\` before \`git push\`
- After pushing: poll Vercel API to confirm the deployment is READY
- If Vercel build fails: read the logs, fix the issue, push again
- Mobile-first responsive design (375px minimum)
- No TypeScript errors, no console warnings
`;

  // Push all three files sequentially (GitHub API requires separate requests)
  await githubFetch(`/repos/${GITHUB_ORG}/${repoName}/contents/VEXCRAFT_BRIEF.md`, {
    method: "PUT",
    body: JSON.stringify({
      message: "chore: add customer brief and tech stack",
      content: briefEncoded,
    }),
  });

  await githubFetch(`/repos/${GITHUB_ORG}/${repoName}/contents/AGENTS.md`, {
    method: "PUT",
    body: JSON.stringify({
      message: "chore: add agent instructions",
      content: Buffer.from(agentsMd).toString("base64"),
    }),
  }).catch((e) => console.warn("[GitHub] Could not push AGENTS.md:", e.message));

  await githubFetch(`/repos/${GITHUB_ORG}/${repoName}/contents/CLAUDE.md`, {
    method: "PUT",
    body: JSON.stringify({
      message: "chore: add CLAUDE.md for coding agent",
      content: Buffer.from(claudeMd).toString("base64"),
    }),
  }).catch((e) => console.warn("[GitHub] Could not push CLAUDE.md:", e.message));
}

export async function getGitHubFileChanges(
  repo: string,
  since: Date
): Promise<GitCommit[]> {
  const commits: Array<{
    sha: string;
    commit: { message: string; author: { name: string; date: string } };
  }> = await githubFetch(
    `/repos/${GITHUB_ORG}/${repo}/commits?since=${since.toISOString()}&per_page=50`
  );

  const result: GitCommit[] = [];

  for (const c of commits.slice(0, 10)) {
    const detail: { files?: Array<{ filename: string }> } = await githubFetch(
      `/repos/${GITHUB_ORG}/${repo}/commits/${c.sha}`
    ).catch(() => ({ files: [] }));

    result.push({
      sha: c.sha.slice(0, 7),
      message: c.commit.message,
      author: c.commit.author.name,
      timestamp: c.commit.author.date,
      filesChanged: (detail.files ?? []).map((f) => f.filename),
    });
  }

  return result;
}
