export const SERVICES = [
  {
    slug: "discord-server",
    name: "Discord Server",
    category: "DISCORD",
    description: "Professional Discord server with channels, roles, bots and custom design.",
    basePrice: 499,
    popular: false,
    icon: "🎮",
    features: ["Channel setup", "Roles & permissions", "Bot integration", "Welcome messages", "Rules & FAQ"],
    packages: [
      { name: "Basic", price: 499, features: ["5 channels", "3 roles", "Welcome bot"] },
      { name: "Pro", price: 999, features: ["15 channels", "10 roles", "Music & moderation bot", "Custom design"] },
      { name: "Premium", price: 1999, features: ["Unlimited", "Custom bot", "Verification", "Ticket system"] },
    ],
  },
  {
    slug: "youtube-banner",
    name: "YouTube Banner & Avatar",
    category: "YOUTUBE",
    description: "Professional channel art that attracts subscribers and reflects your brand.",
    basePrice: 299,
    popular: false,
    icon: "🎬",
    features: ["HD quality", "Custom colors", "Multiple formats", "Logo included", "Revisions"],
    packages: [
      { name: "Banner", price: 299, features: ["1 banner", "2 revisions", "HD export"] },
      { name: "Package", price: 499, features: ["Banner + avatar", "3 revisions", "All formats"] },
      { name: "Complete", price: 799, features: ["Banner + avatar + thumbnail template", "5 revisions", "Source files"] },
    ],
  },
  {
    slug: "streaming-overlay",
    name: "Streaming Overlay",
    category: "STREAMING",
    description: "Professional overlays and alerts for Twitch, YouTube Gaming or TikTok Live.",
    basePrice: 699,
    popular: true,
    icon: "🎯",
    features: ["Custom design", "Alerts & notifications", "Overlay pack", "Scene transitions", "OBS/Streamlabs-ready"],
    packages: [
      { name: "Starter", price: 699, features: ["3 scenes", "Basic alerts", "OBS-ready"] },
      { name: "Streamer", price: 1299, features: ["6 scenes", "Animated alerts", "Panels", "Overlay pack"] },
      { name: "Pro", price: 2499, features: ["Unlimited scenes", "Fully animated pack", "Custom alerts", "Panels"] },
    ],
  },
  {
    slug: "website",
    name: "Website",
    category: "WEBSITE",
    description: "Custom-built website with the features you need, on your chosen tech stack and host.",
    basePrice: 2999,
    popular: true,
    icon: "🌐",
    features: ["Responsive design", "SEO optimized", "Custom tech stack", "Database integration", "Hosting assistance"],
    packages: [
      { name: "Landing Page", price: 2999, features: ["1–5 pages", "Contact form", "Basic SEO", "Mobile-friendly"] },
      { name: "Business", price: 5999, features: ["10+ pages", "CMS", "Payment integration", "Admin panel"] },
      { name: "Custom", price: 9999, features: ["Fully custom", "API integration", "Auth system", "Full support"] },
    ],
    hasTechStack: true,
  },
  {
    slug: "mobile-app",
    name: "Mobile App",
    category: "APP",
    description: "Native or cross-platform app for Android and/or iOS.",
    basePrice: 9999,
    popular: false,
    icon: "📱",
    features: ["Android & iOS", "Custom design", "Push notifications", "API integration", "App Store publishing"],
    packages: [
      { name: "MVP", price: 9999, features: ["5 screens", "Core features", "One platform"] },
      { name: "Standard", price: 19999, features: ["15 screens", "Auth + database", "Both platforms"] },
      { name: "Enterprise", price: 39999, features: ["Unlimited", "Backend included", "Publishing", "6 months support"] },
    ],
    hasTechStack: true,
  },
  {
    slug: "streaming-icons",
    name: "Streaming Icons & Emotes",
    category: "STREAMING",
    description: "Unique sub-badges, emotes and channel point icons for your streaming channel.",
    basePrice: 399,
    popular: false,
    icon: "✨",
    features: ["Twitch/Discord-ready", "Custom emotes", "Sub-badges", "Channel points", "Source files"],
    packages: [
      { name: "Starter", price: 399, features: ["5 emotes", "2 badges"] },
      { name: "Standard", price: 799, features: ["15 emotes", "5 badges", "Channel points icon"] },
      { name: "Full Pack", price: 1499, features: ["30 emotes", "10 badges", "Everything included", "Source files"] },
    ],
  },
];

export const TECH_STACKS = {
  frontend: ["Next.js", "React", "Vue.js", "Nuxt.js", "SvelteKit", "HTML/CSS/JS"],
  backend: ["Node.js", "PHP", "Python (Django)", "Python (FastAPI)", "Laravel", "Express.js"],
  database: ["PostgreSQL", "MySQL", "MongoDB", "SQLite", "Supabase", "PlanetScale"],
  hosting: ["Vercel", "Netlify", "Railway", "DigitalOcean", "AWS", "Hetzner", "Cloudflare Pages"],
};

export const RECOMMENDATIONS: Record<string, { frontend: string; backend: string; database: string; hosting: string; reason: string }> = {
  portfolio: {
    frontend: "Next.js",
    backend: "Next.js API routes",
    database: "PostgreSQL",
    hosting: "Vercel",
    reason: "Perfect for portfolio sites — fast, free hosting and easy to update.",
  },
  ecommerce: {
    frontend: "Next.js",
    backend: "Node.js",
    database: "PostgreSQL",
    hosting: "Railway",
    reason: "Scalable solution for e-commerce with great performance and a reliable database.",
  },
  blog: {
    frontend: "Next.js",
    backend: "Next.js API routes",
    database: "PostgreSQL",
    hosting: "Vercel",
    reason: "Optimal for blogs with SEO and fast load times.",
  },
  webapp: {
    frontend: "React",
    backend: "Node.js",
    database: "PostgreSQL",
    hosting: "DigitalOcean",
    reason: "Flexible and scalable solution for complex web apps.",
  },
};
