export const SUBSCRIPTION_PLANS = [
  {
    slug: "creator",
    name: "Creator Plan",
    price: 29,
    priceGBP: 23,
    priceEUR: 26,
    interval: "month",
    popular: false,
    icon: "🎬",
    tagline: "Perfect for YouTube creators",
    features: [
      "4 YouTube thumbnails per month",
      "1 social media banner update per month",
      "10% off all orders",
      "Email support",
    ],
    bestFor: "YouTubers and content creators who need consistent, on-brand visuals.",
  },
  {
    slug: "streamer",
    name: "Streamer Plan",
    price: 49,
    priceGBP: 39,
    priceEUR: 44,
    interval: "month",
    popular: true,
    icon: "🎮",
    tagline: "Keep your stream fresh",
    features: [
      "5 emotes or badges per month",
      "1 overlay element refresh per month",
      "1 new panel or banner per month",
      "15% off all orders",
      "Priority support",
    ],
    bestFor: "Twitch, YouTube, and TikTok streamers who want a constantly evolving look.",
  },
  {
    slug: "business",
    name: "Business Plan",
    price: 99,
    priceGBP: 79,
    priceEUR: 89,
    interval: "month",
    popular: false,
    icon: "💼",
    tagline: "Your digital team on retainer",
    features: [
      "3 design deliverables per month (your choice)",
      "1 copywriting piece per month (500 words)",
      "Monthly SEO snapshot report",
      "Monthly 30-min strategy call",
      "20% off all orders",
      "Priority support",
    ],
    bestFor: "Small businesses that need ongoing creative and digital support without hiring in-house.",
  },
  {
    slug: "growth",
    name: "Growth Plan",
    price: 199,
    priceGBP: 159,
    priceEUR: 179,
    interval: "month",
    popular: false,
    icon: "🚀",
    tagline: "Full-service creative partner",
    features: [
      "6 design deliverables per month (your choice)",
      "2 copywriting pieces per month (1,000 words each)",
      "Monthly SEO audit + action plan",
      "1 video short per month",
      "Bi-weekly strategy calls",
      "Dedicated project coordinator",
      "Priority queue for all orders",
      "25% off all orders",
      "Monthly performance report",
    ],
    bestFor: "Growing brands that need a full creative team without the overhead.",
  },
];

export const BUNDLES = [
  {
    slug: "streamer-starter",
    name: "Streamer Starter",
    icon: "🎮",
    description: "Everything you need to start streaming with a professional look.",
    services: ["Streaming Overlay (Starter)", "Streaming Emotes (Starter)", "YouTube Banner"],
    originalPrice: 247,
    originalPriceGBP: 197,
    originalPriceEUR: 222,
    bundlePrice: 199,
    bundlePriceGBP: 159,
    bundlePriceEUR: 179,
    discount: 19,
    popular: true,
  },
  {
    slug: "creator-kit",
    name: "Creator Kit",
    icon: "🎬",
    description: "Complete YouTube presence — channel art, thumbnails, and social media.",
    services: ["YouTube Banner (Package)", "YouTube Thumbnails (10 Pack)", "Social Media Kit (Starter)"],
    originalPrice: 217,
    originalPriceGBP: 173,
    originalPriceEUR: 195,
    bundlePrice: 169,
    bundlePriceGBP: 135,
    bundlePriceEUR: 152,
    discount: 22,
    popular: false,
  },
  {
    slug: "full-brand",
    name: "Full Brand Package",
    icon: "✨",
    description: "Complete brand identity — logo, social presence, and email templates.",
    services: ["Logo & Branding (Brand Kit)", "Social Media Kit (Creator)", "Email Templates (Single)"],
    originalPrice: 377,
    originalPriceGBP: 301,
    originalPriceEUR: 339,
    bundlePrice: 299,
    bundlePriceGBP: 239,
    bundlePriceEUR: 269,
    discount: 21,
    popular: false,
  },
  {
    slug: "discord-complete",
    name: "Discord Complete",
    icon: "💬",
    description: "Professional Discord server with matching branding and emotes.",
    services: ["Discord Server (Pro)", "Streaming Emotes (Standard)", "Logo & Branding (Logo)"],
    originalPrice: 357,
    originalPriceGBP: 285,
    originalPriceEUR: 321,
    bundlePrice: 279,
    bundlePriceGBP: 223,
    bundlePriceEUR: 251,
    discount: 22,
    popular: false,
  },
  {
    slug: "business-launch",
    name: "Business Launch",
    icon: "✨",
    description: "Everything you need to launch your brand online — identity, copy, and search visibility.",
    services: ["Logo & Branding (Brand Kit)", "Copywriting (Starter)", "SEO Audit (Quick Scan)"],
    originalPrice: 397,
    originalPriceGBP: 317,
    originalPriceEUR: 357,
    bundlePrice: 299,
    bundlePriceGBP: 239,
    bundlePriceEUR: 269,
    discount: 25,
    popular: false,
  },
  {
    slug: "growth-accelerator",
    name: "Growth Accelerator",
    icon: "📈",
    description: "Full growth package — content, copy, and SEO working together to grow your audience.",
    services: ["Social Media Kit (Creator)", "Copywriting (Growth)", "SEO Audit (Full Audit)"],
    originalPrice: 727,
    originalPriceGBP: 581,
    originalPriceEUR: 653,
    bundlePrice: 549,
    bundlePriceGBP: 439,
    bundlePriceEUR: 493,
    discount: 24,
    popular: false,
  },
];

export const UPSELLS: Record<string, { title: string; description: string; slug: string; price: number; priceGBP: number; priceEUR: number }[]> = {
  "youtube-banner": [
    { title: "Add YouTube Thumbnails", description: "5 matching thumbnails for your channel", slug: "youtube-thumbnails", price: 29, priceGBP: 23, priceEUR: 26 },
    { title: "Social Media Kit", description: "Match your YouTube look across all platforms", slug: "social-media-kit", price: 69, priceGBP: 55, priceEUR: 62 },
  ],
  "youtube-thumbnails": [
    { title: "YouTube Banner & Avatar", description: "Complete your channel look", slug: "youtube-banner", price: 59, priceGBP: 47, priceEUR: 54 },
    { title: "Social Media Kit", description: "Same style across all platforms", slug: "social-media-kit", price: 69, priceGBP: 55, priceEUR: 62 },
  ],
  "streaming-overlay": [
    { title: "Matching Emotes", description: "Emotes that match your overlay style", slug: "streaming-icons", price: 39, priceGBP: 31, priceEUR: 35 },
    { title: "YouTube Banner", description: "Matching channel art for YouTube", slug: "youtube-banner", price: 59, priceGBP: 47, priceEUR: 54 },
  ],
  "streaming-icons": [
    { title: "Streaming Overlay", description: "Complete your stream with matching overlays", slug: "streaming-overlay", price: 149, priceGBP: 119, priceEUR: 134 },
    { title: "Gaming Profile Pack", description: "Match your look across gaming platforms", slug: "gaming-profile", price: 39, priceGBP: 31, priceEUR: 35 },
  ],
  "discord-server": [
    { title: "Logo & Branding", description: "Professional logo for your server", slug: "logo-branding", price: 79, priceGBP: 63, priceEUR: 71 },
    { title: "Custom Emotes", description: "Emotes for your Discord community", slug: "streaming-icons", price: 39, priceGBP: 31, priceEUR: 35 },
  ],
  "logo-branding": [
    { title: "Social Media Kit", description: "Apply your new brand across all platforms", slug: "social-media-kit", price: 69, priceGBP: 55, priceEUR: 62 },
    { title: "Email Templates", description: "Branded emails matching your new identity", slug: "email-templates", price: 99, priceGBP: 79, priceEUR: 89 },
  ],
  "social-media-kit": [
    { title: "Logo & Branding", description: "Start with a proper brand identity", slug: "logo-branding", price: 79, priceGBP: 63, priceEUR: 71 },
    { title: "YouTube Thumbnails", description: "Matching thumbnails for your channel", slug: "youtube-thumbnails", price: 29, priceGBP: 23, priceEUR: 26 },
  ],
  "gaming-profile": [
    { title: "Streaming Overlay", description: "Match your gaming profiles with stream look", slug: "streaming-overlay", price: 149, priceGBP: 119, priceEUR: 134 },
    { title: "Streaming Emotes", description: "Custom emotes matching your style", slug: "streaming-icons", price: 39, priceGBP: 31, priceEUR: 35 },
  ],
  "email-templates": [
    { title: "Logo & Branding", description: "Brand identity to match your emails", slug: "logo-branding", price: 79, priceGBP: 63, priceEUR: 71 },
    { title: "Social Media Kit", description: "Consistent branding everywhere", slug: "social-media-kit", price: 69, priceGBP: 55, priceEUR: 62 },
  ],
  "notion-templates": [
    { title: "Logo & Branding", description: "Professional brand for your business", slug: "logo-branding", price: 79, priceGBP: 63, priceEUR: 71 },
    { title: "Email Templates", description: "Branded emails for your clients", slug: "email-templates", price: 99, priceGBP: 79, priceEUR: 89 },
  ],
};
